version: "2"
networks:
  flightmap-network:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    networks:
      - flightmap-network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
#    volumes:
#      - '../docker_volumes/zookeeper:/bitnami/zookeeper'
  kafka-1:
    image: 'bitnami/kafka:2.6.0'
    networks:
      - flightmap-network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#    volumes:
#      - '../docker_volumes/kafka-1:/bitnami/kafka'
  mongo:
    image: mongo:4.4.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: flight
    networks:
      - flightmap-network
    ports:
      - 27017:27017

#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example


#    volumes:
#    - '../docker_volumes/postgres:/var/lib/postgresql/data'
