version: "2"
networks:
  flightmap-network:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    networks:
      - flightmap-network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - '../docker_volumes/zookeeper:/bitnami/zookeeper'
  kafka-1:
    image: 'bitnami/kafka:2.6.0'
    networks:
      - flightmap-network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST_NAME}:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - '../docker_volumes/kafka-1:/bitnami/kafka'
  postgres:
    image: postgres:13
    networks:
      - flightmap-network
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
    - '../docker_volumes/postgres:/var/lib/postgresql/data'
